### PR TITLE
use {{t ...}}, it stops working

### PR DESCRIPTION
**Pull request by princemaple**
changed hard coded "Loading" to use {{t "loading"}}

added {{t "yolo"}} to weather page

now both loading page and weather page stops working.

another discovery is that the bookmark app is also not working,
it is pretty much in the same situation.
a frame is displayed for the app and no content is in it.
bm

### CODE REVIEW

**Comment by jwswj** [comment]
Looks like you are using our new translation approach that we are planning to deploy today.

2 options:
- Wait for this to hit production either today or tomorrow
- Change back to the old translation method (no `title` & `value`) - https://github.com/zendesk/bookmarks_app/blob/c09118311f3a0d55c8bc619634d9c461833af795/translations/en.json Also don't need `package` defined in the old translation approach.

**Comment by princemaple** [comment]
Hmmm, ok. Thanks.

I knew it has something to do with version.

I'll clean up the unneeded part and wait.

**Comment by jwswj** [comment]
@princemaple code is now live, so you should be able to get this working. 

You'll need to make sure all translations have a title/value pair. Including description, label, helpText.

You can use zat - https://github.com/zendesk/zendesk_apps_tools `gem install zendesk_apps_tools` to test validation before uploading if you like.

**Comment by princemaple** [comment]
@jwswj Thanks for mentioning ZAT, Jason. It's very useful.

The app is now working all right.

**Comment by jwswj** [comment]
Good to hear

**Pull request merged**
